name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/GerrKoff.Monitoring.sln

    - name: Build
      run: dotnet build --no-restore src/GerrKoff.Monitoring.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal src/GerrKoff.Monitoring.sln

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
